#include "Variables.h"
#include "ProcVar.h"
#include <Equipment.h>
#include <Status.h>
#include <WaterHeatControl.h>
#include "GambainoCommon.h"
#include <BrewCoreCommon.h>

unsigned long int lastPressureReceived = 0;


void configVariables()
{
    //MLTTopLevel.setLatency(5*SECONDS);
    MLTPump.setLatency    (PUMPLATENCY);
    HLTPump.setLatency  (PUMPLATENCY);
    BKPump.setLatency  (PUMPLATENCY);
    ColdBankPump.setLatency(10*SECONDS); /***** Constante ****/
    
//    Fermenter1Control.setLatency  (1  * MINUTES);
//    Fermenter2Control.setLatency  (1  * MINUTES);
    ColdBankControl  .setLatency  (2  * MINUTES);

   // ProcVar::I2CSetInvertedCluster(RELAYSA_ADDR);
    //ProcVar::I2CSetInvertedCluster(RELAYSB_ADDR);
    /*ProcVar::I2CSetInvertedCluster(RELAYSC_ADDR);
    ProcVar::I2CSetInvertedCluster(RELAYSD_ADDR);
    ProcVar::I2CSetInvertedCluster(RELAYSE_ADDR);*/
    
    
    ProcVar::I2CSetDualBitCluster(VALVESJ_ADDR);
    ProcVar::I2CSetDualBitCluster(VALVESK_ADDR);
    ProcVar::I2CSetDualBitCluster(VALVESL_ADDR);
    ProcVar::I2CSetDualBitCluster(VALVESM_ADDR);
    ProcVar::I2CSetDualBitCluster(VALVESN_ADDR);
}


void warmBoot()       // ignore any on going process, set values to stand by status
{
    Status    = 0;
}

void processDerivedVars()
{
}

void quickI2CSetZeros() {
  byte clusters[] = {RELAYSA_ADDR, RELAYSB_ADDR, RELAYSC_ADDR, RELAYSD_ADDR, RELAYSE_ADDR,
                     VALVESJ_ADDR, VALVESK_ADDR, VALVESL_ADDR, VALVESM_ADDR, VALVESN_ADDR};
  for (byte i=0; i<sizeof(clusters); i++) {
    Wire.beginTransmission(int(clusters[i]));
    Wire.write(0);
    Wire.endTransmission(true);
  }
}


// control
DECL('C',Power12VOn,                    P12  ,MODEOUTPUT,           NOTPERSISTENT,      0,        ADDRPOWER12VON,      DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',Power12VBlock,                 B12  ,MODEOUTPUT,           NOTPERSISTENT,      0,        ADDRPOWER12VBLOCK,   DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',OnGoingProgram,                     ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',ProgramParams,                      ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',Status,                             ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',SubStatus,                          ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',IPCStatus,                          ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',EndStatus,                          ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',SkipToNextStatus,                   ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',CirculationMode,                    ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',LineConfiguration,                  ,MODEFLOAT,            PROCESSPERSISTENCE, 3,        NOPIN,               DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('X',TimeInStatus,                       ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGPROCESS, NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('X',IPCTimeInStatus,                    ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',Led1,                               ,MODEOUTPUTTIMECTRL,   NOTPERSISTENT,      0,        ADDRLED1,            DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',Led2,                               ,MODEOUTPUTTIMECTRL,   NOTPERSISTENT,      0,        ADDRLED2,            DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('C',Buzzer,                             ,MODEOUTPUTTIMECTRL,   NOTPERSISTENT,      0,        ADDRBUZZER,          DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)

// recipe
DECL('R',RcpGrainWeight,                     ,MODEFLOAT,            CONFIGPERSISTENCE,  23,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpMashTime,                        ,MODEFLOAT,            CONFIGPERSISTENCE,  90,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpMashTemp,                        ,MODEFLOAT,            CONFIGPERSISTENCE,  66.5,     NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpWaterGrainRatio,                 ,MODEFLOAT,            CONFIGPERSISTENCE,  2.5,      NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpRampGrainWeight,                 ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpRampTime,                        ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpRampTemp,                        ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpCaramelizationBoil,              ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpBoilTime,                        ,MODEFLOAT,            CONFIGPERSISTENCE,  90,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpBoilTemp,                        ,MODEFLOAT,            CONFIGPERSISTENCE,  100,      NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpWhirlpoolTerminalTemp,           ,MODEFLOAT,            CONFIGPERSISTENCE,  55,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpWhirlpoolHoppingTime,            ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpWhirlpoolHoppingTemp,            ,MODEFLOAT,            CONFIGPERSISTENCE,  76,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpWhirlpoolMinimumTime,            ,MODEFLOAT,            CONFIGPERSISTENCE,  15,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpWhirlpoolRestTime,               ,MODEFLOAT,            CONFIGPERSISTENCE,  15,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpInoculationTemp,                 ,MODEFLOAT,            CONFIGPERSISTENCE,  18,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpFirstWortHopping,                ,MODEFLOAT,            CONFIGPERSISTENCE,  1,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpAddition1,                       ,MODEFLOAT,            CONFIGPERSISTENCE,  15,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpAddition2,                       ,MODEFLOAT,            CONFIGPERSISTENCE,  10,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpAddition3,                       ,MODEFLOAT,            CONFIGPERSISTENCE,  3,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpAddition4,                       ,MODEFLOAT,            CONFIGPERSISTENCE,  -1,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpAddition5,                       ,MODEFLOAT,            CONFIGPERSISTENCE,  -1,       NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpFermenterCleaning,               ,MODEFLOAT,            CONFIGPERSISTENCE,  1,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpTargetFermenter,                 ,MODEFLOAT,            CONFIGPERSISTENCE,  1,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpTopupWater,                      ,MODEFLOAT,            CONFIGPERSISTENCE,  1,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpKettleSourFirstBoilTime,         ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpKettleSourSouringTemp,           ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('R',RcpStartTime,                       ,MODEFLOAT,            CONFIGPERSISTENCE,  7,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS) 
DECL('R',RcpBatchNum,                        ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS) 
DECL('R',FMT1BatchNum,                       ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS) 
DECL('R',FMT2BatchNum,                       ,MODEFLOAT,            CONFIGPERSISTENCE,  0,        NOPIN,               DATALOGOFF,     JSONRECIPE,   NOTINVERTED, AUTOOVERRIDE,   NODALLAS)

// level and pressure control
DECL('L',MLTTopLevel,                        ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS) 
DECL('L',HLTVolume,                          ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('L',HLTTargetVolume,                    ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('L',BKLevel,                            ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS) 
DECL('L',TransferVolume,                     ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('L',TransferFlow,                       ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('L',HLT2MLTFlow,                        ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)

// Water Control
DECL('W',HotWaterIn,                         ,MODEOUTPUT,           NOTPERSISTENT,      0,        ADDRHOTWATERIN,      DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('W',ColdWaterIn,                        ,MODEOUTPUT,           NOTPERSISTENT,      0,        ADDRCOLDWATERIN,     DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('W',WaterInTarget,                      ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('W',WaterInFlow,                        ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGOFF,     JSONPROCESS,  NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('W',WaterInETA,                         ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGOFF,     JSONPROCESS,  NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('I',DrainBlock,                         ,MODEOUTPUT,           NOTPERSISTENT,      1,        ADDRDRAINBLOCK,      DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)


// heater control
DECL('H',HLTHeater,                     HH   ,MODEOUTPUT,           NOTPERSISTENT,      0,        ADDRHLTHEATER,       DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('H',BKHeater,                      BG   ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('H',BKHeaterL,                     BGL  ,MODEOUTPUT,           NOTPERSISTENT,      0,        ADDRBKHEATERL,       DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('H',BKHeaterH,                     BGH  ,MODEOUTPUT,           NOTPERSISTENT,      0,        ADDRBKHEATERH,       DATALOGOFF,     NOJSON,       NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('H',TopUpHeater,                   TUH  ,MODEOUTPUT,           NOTPERSISTENT,      0,        ADDRTOPUPHEATER,     DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('H',Dehumidifier,                  DH   ,MODEOUTPUT,           NOTPERSISTENT,      0,        ADDRDEHUMIDIFIER,    DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)


// Mash temperature control 
DECL('H',HeatAdditiveCorrection,             ,MODEFLOAT,            CONFIGPERSISTENCE,  2,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('H',HeatDampeningFactor,                ,MODEFLOAT,            CONFIGPERSISTENCE,  0.8,      NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('H',HeatCoilEfficiency,                 ,MODEFLOAT,            NOTPERSISTENT,      0.8,      NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)

// Hot side valves 
DECL('V',HLTValve,                      HV   ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRHLTVALVE,        DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('L',HLTWaterIn,                    HWI  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRHLTWATERIN,      DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('L',HLTDrain,                      HDI  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRHLTDRAIN,        DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)

DECL('V',MLTValveA,                     MVA  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRMLTVALVEA,       DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('V',MLTValveB,                     MVB  ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRMLTVALVEB,       DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('V',MLTDrain,                      MDV  ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRMLTDRAINVALVE,   DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)

DECL('V',BKValveA,                      KVA  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRBKVALVEA,        DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('V',BKValveB,                      KVB  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRBKVALVEB,        DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('V',WhirlpoolValve,                WPV  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRWHIRLPOOLVALVE,  DATALOGPROCESS, JSONPROCESS,  INVERTED, NORMALOVERRIDE, NODALLAS)
DECL('V',BKWaterIn,                     KWI  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRBKWATERINVALVE,  DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('V',BKDrain,                       KDV  ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRBKDRAINVALVE,    DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)


// Hot side pumps
DECL('P',MLTPump,                       MP   ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRMLTPUMP,         DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('P',HLTPump,                       HP   ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRHLTPUMP,         DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('P',BKPump,                        KP   ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRBKPUMP,          DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)


// Hot side temperature
DECL('T',HLTTargetTemp,                      ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('T',HLTTemp,                            ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS1,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, HLTThermometer)
DECL('T',HLTOutTemp,                         ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS1,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, HLTOutThermometer)
DECL('T',MLTTopTemp,                         ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS1,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, MLTTopThermometer)
DECL('T',MLTTemp,                            ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS1,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, MLTThermometer)
DECL('T',MLTOutTemp,                         ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS1,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, MLTBottomThermometer)
DECL('T',MLTTargetTemp,                      ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('T',BKTargetTemp,                       ,MODEFLOAT,            PROCESSPERSISTENCE, 0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('T',BKTemp,                             ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS2,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, BKThermometer)
DECL('T',TopUpWaterTemp,                     ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS2,             DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, TopUpWaterThermometer)
DECL('T',FermenterTemp,                      ,MODEFLOAT,            NOTPERSISTENT,     NOTaTEMP,  NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('T',EnvironmentTemp,                    ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS2,             DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, EnvironmentThermometer)


// Chillers
DECL('X',Chiller1,                      C1V  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRCHILLER1VALVE,   DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('X',ColdBankPump,                  CBP  ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRCOLDBANKPUMP,    DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('X',Chiller1Temp,                       ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS2,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, Chiller1Thermometer)
DECL('X',Chiller2Temp,                       ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS3,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, Chiller2Thermometer)
DECL('X',Chiller2WasteTemp,                  ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS3,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, Chiller2WasteThermometer)
DECL('X',TransferAvgTemp,                    ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('X',ColdBankWaterIn,                    ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRCOLDBANKWATERIN, DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('X',ColdBankTemp,                       ,MODEDALLAS,           NOTPERSISTENT,      0,        DALLAS3,             DATALOGPROCESS, JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, ColdBankThermometer)
DECL('X',ColdBankTargetTemp,            CBT  ,MODEFLOAT,            PROCESSPERSISTENCE,NOTaTEMP,  NOPIN,               DATALOGOFF,     JSONCOLDSIDE, NOTINVERTED, AUTOOVERRIDE,   NODALLAS)
DECL('X',ColdBankControl,               CB   ,MODEOUTPUTTIMECTRL,   NOTPERSISTENT,      0,        ADDRCOLDBANKCONTROL, DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('X',ColdBankValve,                 CBV  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRCOLDBANKLVALVE,  DATALOGOFF,     JSONPROCESS,  INVERTED, NORMALOVERRIDE, NODALLAS)


// KEG CIP 
DECL('K', KegPump,                      KP   ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRKEGPUMP,         DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('K', KegWaterIn,                   KWI  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRKEGWATERIN,      DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('K', KegDetergentValve,            KDV  ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRKEGDETERGVALVE,  DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('K', KegDetergentPump,             KDP  ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRKEGDETERGPUMP,   DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('K', KegDrain,                     KDV  ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRKEGDRAINVALVE,   DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('K', KegCycle,                     KC   ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, 0,        ADDRKEGCYCLE,        DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('K', KegLiquidSensor,              KLS  ,MODEFLOAT,            NOTPERSISTENT,      0,        NOPIN,               DATALOGOFF,     JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)

// FMT CIP 
DECL('I',FMTWaterIn,                   CW    ,MODEOUTPUT,           PROCESSPERSISTENCE, CLOSED,   ADDRFMTWATERINVALVE,   DATALOGOFF,   JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('I',FMTPump,                      CP    ,MODEOUTPUT,           PROCESSPERSISTENCE, 0,        ADDRFMTPUMP,           DATALOGOFF,   JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('I',FMTDrain,                     CD    ,MODEOUTPUT,           PROCESSPERSISTENCE, OPEN,     ADDRFMTDRAINVALVE,     DATALOGOFF,   JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('I',FMTCycle,                     CC    ,MODEOUTPUTTIMECTRL,   PROCESSPERSISTENCE, OPEN,     ADDRFMTCYCLEVALVE,     DATALOGOFF,   JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)

// Pot cleaner
DECL('P',PotCleanerWaterIn,            PWV   ,MODEOUTPUT,           PROCESSPERSISTENCE, CLOSED,   ADDRPOTCLEANERWATERIN, DATALOGOFF,   JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)
DECL('P',PotCleanerDrain,              PDV   ,MODEOUTPUT,           PROCESSPERSISTENCE, OPEN,     ADDRPOTCLEANERDRAIN,   DATALOGOFF,   JSONPROCESS,  NOTINVERTED, NORMALOVERRIDE, NODALLAS)




