[platformio]
default_envs = Povoto
src_dir = .
build_dir = c:\ArduinoCompile\Povoto


[env:Povoto]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200
upload_protocol = esptool

lib_deps =
    bodmer/TFT_eSPI@^2.5.30
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    ricmoo/QRCode@^0.0.1
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0
	  ayushsharma82/ElegantOTA@^3.1.7    

lib_extra_dirs =
    a:\Nuvem\Gambaino\Prog\Common

lib_ignore =
    ESPAsyncWebServer
    ESPAsyncTCP
    RPAsyncTCP
    AsyncTCP

; Perfil alinhado ao projeto pequeno que funcionou na mesma placa.
board_build.arduino.memory_type = qio_opi
board_build.filesystem = littlefs

build_flags =
    -DUSER_SETUP_LOADED
  	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -include include/User_Setup.h
    -DAPP_PROJECT_NAME='"Povoto"'
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DUI_BMP_USE_PSRAM=1


[env:PovotoDebug]
extends = env:Povoto

build_type = debug

debug_tool = esp-builtin
debug_init_break = tbreak setup