; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;lib_dir = a:\Dropbox\Arduino\Sketches\libraries
src_dir = .
build_dir = c:\ArduinoCompile\Povoto

[env:Povoto]
platform = espressif32@6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
  bodmer/TFT_eSPI@^2.5.30
	esphome/ESPAsyncWebServer-esphome@^3.2.2
	ricmoo/QRCode@^0.0.1
	paulstoffregen/OneWire@^2.3.7
	milesburton/DallasTemperature@^3.11.0
;	paulstoffregen/OneWire@^2.3.7
;	milesburton/DallasTemperature@^3.11.0
;	marian-craciunescu/ESP32Ping@^1.7
;		adafruit/Adafruit INA219@^1.2.3
lib_extra_dirs = a:\Nuvem\Gambaino\Prog\Common
lib_ignore = ESPAsyncWebServer, ESPAsyncTCP, RPAsyncTCP, AsyncTCP

build_flags =
  -DUSER_SETUP_LOADED
  -include include/User_Setup.h
  -DAPP_PROJECT_NAME='"Povoto"'

board_build.filesystem = littlefs
